# Site settings
title: LáVouEu
email: lavoueu.blog@gmail.com
description: Blog de viagem e fotografia. Tenha a melhor experência fotográfica, saiba como chegar, onde se posicionar e como fotografar cada lugar que você visita.
# baseurl: "/writer/" # the subpath of your site, e.g. /blog
url: "http://www.lavoueu.blog.br" # the base hostname & protocol for your site
enable_retina: false # Documentação: http://imulus.github.io/retinajs/
permalink: /:title
nav_list:
  Home : ['Home', '/', 'fa-home']
  Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/michelle', 'fa-user']

single_footer: '<p>Vamos viajar e fotografar em diversos lugares do mundo! - LáVouEu - Copyright &copy; <script> document.write(new Date().getFullYear()) </script> - <a href="http://www.lavoueu.blog.br">Últimos artigos</a></p>'  #aparece nas páginas avulsas, as com "layout: page"
footer_links:
    Sobre: ['Sobre este blog', '/sobre']
    Contato: ['Contato', '/contato']

repository: https://github.com/filipemscampos/filipemscampos.github.io.git

# Build settings
markdown: kramdown

timezone: America/Sao_Paulo

gems:
- jekyll-textile-converter


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: post-sidebar
      author_name : Filipe M. S. de Campos
      author_url : author/filipe
      author_avatar: filipe
      show_avatar : false
      read_time : 0
